const { Pool } = require('pg');

// ─────────────────────────────────────────────
// Neon PostgreSQL connection
// ─────────────────────────────────────────────

if (!process.env.DATABASE_URL) {
  throw new Error('❌ DATABASE_URL is not set.');
}

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,

  ssl: {
    rejectUnauthorized: false,
  },

  max: 10,
  connectionTimeoutMillis: 10000,
  idleTimeoutMillis: 30000,
});

pool.on('error', (err) => {
  console.error('❌ Unexpected PostgreSQL pool error:', err);
});

// ─────────────────────────────────────────────
// Test connection
// ─────────────────────────────────────────────

async function testConnection() {
  const client = await pool.connect();

  try {
    await client.query('SELECT 1');
    console.log('✅ Connected to Neon PostgreSQL');
  } finally {
    client.release();
  }
}

// ─────────────────────────────────────────────
// Initialize database
// ─────────────────────────────────────────────

async function initDatabase() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username TEXT NOT NULL,
      email TEXT NOT NULL,
      password_hash TEXT NOT NULL,
      avatar TEXT DEFAULT NULL,
      bio TEXT DEFAULT NULL,
      role TEXT NOT NULL DEFAULT 'user'
        CHECK (role IN ('user', 'admin')),
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE UNIQUE INDEX IF NOT EXISTS users_username_lower_idx
      ON users (LOWER(username));

    CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_idx
      ON users (LOWER(email));

    CREATE INDEX IF NOT EXISTS idx_users_email
      ON users(email);

    CREATE INDEX IF NOT EXISTS idx_users_username
      ON users(username);


    CREATE TABLE IF NOT EXISTS videos (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title TEXT NOT NULL,
      description TEXT DEFAULT NULL,
      filename TEXT NOT NULL,
      thumbnail TEXT DEFAULT NULL,
      duration DOUBLE PRECISION DEFAULT NULL,
      file_size BIGINT NOT NULL,
      mime_type TEXT NOT NULL,
      views INTEGER NOT NULL DEFAULT 0,
      user_id INTEGER NOT NULL,
      visibility TEXT NOT NULL DEFAULT 'public'
        CHECK (visibility IN ('public', 'private')),
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

      CONSTRAINT fk_videos_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
    );

    CREATE INDEX IF NOT EXISTS idx_videos_user_id
      ON videos(user_id);

    CREATE INDEX IF NOT EXISTS idx_videos_created_at
      ON videos(created_at DESC);

    CREATE INDEX IF NOT EXISTS idx_videos_visibility
      ON videos(visibility);
  `);

  console.log('✅ Neon database schema ready');
}

module.exports = {
  pool,
  initDatabase,
  testConnection,
};